from supabase import create_client
import os
from dotenv import load_dotenv

load_dotenv()
supabase = create_client(os.getenv("SUPABASE_URL"), os.getenv("SUPABASE_KEY"))

fake_token = "eyJhbGciOiJFUzI1NiIsImtpZCI6IjNiM2RkNDRmLWY4NmQtNGM4My1iYWQ5LWM1YTdmMWVlNGNmMCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3dieGlxc2dlemp2cGNtY2doaHJ4LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyMmFjZjk3Yi1hMDJmLTQ5MWQtYWE2OS1iNWRhM2U1ZGYxMDkiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg4NzgyOTY0LCJpYXQiOjE3ODg3NzkzNjQsImVtYWlsIjoidGVzdHVzZXIxQGV4YW1wbGUuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InRlc3R1c2VyMUBleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6IjIyYWNmOTdiLWEwMmYtNDkxZC1hYTY5LWI1ZGEzZTVkZjEwOSJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzg4Nzc5MzY0fV0sInNlc3Npb25faWQiOiJiMzU4YTc2Yy00NDM5LTQxNDQtYTdjYy05ZTFhODkzMWNkM2EiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.vmQGHkZbCtXNNvs4oiLpKuZF1XoAmPYUC3nndJIVhUJLt78Pko8IXk0jzyMkPRpBvZBqMYDpAkYIvYoAe4gg4Q"

try:
    response = supabase.auth.get_user(fake_token)
    print("NO EXCEPTION. Response was:")
    print(response)
except Exception as e:
    print("EXCEPTION RAISED:")
    print(type(e), e)